trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

# Build Docker Image
- script: |
    docker build -t axe-scanner .
  displayName: Build Accessibility Scanner Image

# Run Accessibility Scanner Extension
- task: CavissonAccessibilityScanner@1
  displayName: Run Accessibility Scan
  inputs:
    targetUrl: 'https://www.cricbuzz.com/'
    failOnCritical: false