trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

# Run Accessibility Scanner Extension Task
- task: AccessibilityScanner@1
  displayName: 'Run Accessibility Scanner'
  inputs:
    targetUrl: 'https://www.cricbuzz.com'

# Publish JSON Report
- task: PublishBuildArtifacts@1
  displayName: 'Publish JSON Report'
  inputs:
    pathToPublish: '$(System.DefaultWorkingDirectory)/_temp'
    artifactName: 'AccessibilityJSON'

# Publish HTML Report
- task: PublishBuildArtifacts@1
  displayName: 'Publish HTML Report'
  inputs:
    pathToPublish: '$(System.DefaultWorkingDirectory)/_temp'
    artifactName: 'AccessibilityHTML'