# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: AccessibilityScanner@1
  inputs:
    cavAccessibilityServiceConnection: 'Accessibility_connection'
    targetUrl: 'https://netcloud4-15-u24.cav-test.com:4444/UnifiedDashboard/#/login'
