trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

# Run Accessibility Scanner
- task: AccessibilityScanner@1
  displayName: 'Run Accessibility Scanner'
  inputs:
    targetUrl: 'https://www.cricbuzz.com'

# Publish Accessibility Reports
- task: PublishBuildArtifacts@1
  displayName: 'Publish Accessibility Reports'
  inputs:
    pathToPublish: '$(System.DefaultWorkingDirectory)/task/scanner/reports'
    artifactName: 'AccessibilityReports'