# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: AccessibilityScanner@1
  inputs:
    cavAccessibilityServiceConnection: 'new_accessibility_connection'
    targetUrl: 'https://10.10.10.115:4444'
