trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

# Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

# Install dependencies
- script: |
    npm install
  displayName: 'Install Dependencies'

# Install Playwright browsers
- script: |
    npx playwright install --with-deps
  displayName: 'Install Playwright'

# Run accessibility scan
- script: |
    node scan.js https://netcloud4-15-u24.cav-test.com:4444/UnifiedDashboard/#/login
  displayName: 'Run Accessibility Scan'

# Generate HTML report
- script: |
    node generate-report.js
  displayName: 'Generate HTML Report'

# Publish report artifact
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '.'
    artifactName: 'AccessibilityReport'
  displayName: 'Publish Accessibility Report'

- task: CavissonCodeAnalyzer@1
  inputs:
      cavissonAnalyzerServiceConnection: 'cav'
      project: 'new_proj'
